export enum ThreatType {
  MASS_DATA_READ = "MASS_DATA_READ",
  PERMISSION_CHANGE = "PERMISSION_CHANGE",
  OFF_HOURS_ACCESS = "OFF_HOURS_ACCESS",
  SUSPICIOUS_LOGIN = "SUSPICIOUS_LOGIN",
  DATA_EXFILTRATION = "DATA_EXFILTRATION"
}