export enum RecommendationMetric {
  MTTD = "MTTD",
  MTTR = "MTTR",
  FALSE_ALARM_RATE = "FALSE_ALARM_RATE",
  INCIDENTS_BY_CATEGORY = "INCIDENTS_BY_CATEGORY",
  TOTAL_ALERTS = "TOTAL_ALERTS",
  OPEN_ALERTS = "OPEN_ALERTS",
  RESOLVED_ALERTS = "RESOLVED_ALERTS",
  SCORE = "SCORE"
}